Adding first version of authentication and authorization
valocode/bubbly pull request #34
Opened 2021-03-17 07:41 UTC by jlarfors

First draft of authn and authz.

There are some things to consider before merging this:
1. This doesn't actually change anything unless you opt in for authentication and multitenancy
2. There are services now in the docker-compose file that not everyone will have access to... I wonder if we should set up something else for developing with `bubbly-auth` in the meantime? I can use skaffold or something locally
3. How do the conditional routes (e.g with multitenancy the base API route is `/api/v1/o/:organization`) affect swagger and the Bubbly CLI?

Open to feedback and suggestions! This is a WIP so there is still work to add swagger docs and things

2021-03-24 14:15 UTC, nate-droid approved these changes

2021-03-24 14:15 UTC, nate-droid commented on server/routes.go
> +	// If multitenancy is enabled, add it the URL path
Really nice and clean! Love it.

2021-03-24 14:15 UTC, nate-droid commented on server/middleware.go
> +		// fmt.Printf("\n\nWHAAAAT! It worked!\n%v\n", reqAuth)
I love the surprise 😆

2021-03-24 14:15 UTC, nate-droid commented on server/auth.go
> +func (s *Server) authorize(c echo.Context) error {
I really like this approach as well. Nice and clean!

2021-03-24 17:05 UTC, jlarfors commented on server/middleware.go
> +		// fmt.Printf("\n\nWHAAAAT! It worked!\n%v\n", reqAuth)
Oops... it's fixed!

2021-03-25 07:01 UTC, benmarsden commented
> 2\. How do the conditional routes (e.g with multitenancy the base API route is `/api/v1/o/:organization`) affect swagger and the Bubbly CLI?

I think this may break the CLI: the CLI makes requests through the bubbly HTTP Client, which has static routes defined like so:

```go
// client/query.go
http.Post(fmt.Sprintf("%s/api/v1/graphql", c.HostURL), "application/json", bytes.NewBuffer(jsonReq)),
```

So I think you'll need to update this request logic to accommodate the new base route.

I do not have the knowledge to comment on swagger.

2021-03-25 07:04 UTC, benmarsden requested changes
Update Bubbly's HTTP Client to handle differing base routes.

2021-03-29 08:12 UTC, olliefr requested changes
Just some Swagger-related stuff... 🙃

2021-03-29 08:18 UTC, jlarfors commented on .github/workflows/integration.yaml
> +          docker-compose up -d postgres bubbly
Yup, fair point...

2021-03-29 08:20 UTC, jlarfors commented on server/auth.go
> +		return nil, echo.NewHTTPError(http.StatusInternalServerError, "failed to read response from auth service: "+err.Error())
Nope, it shouldn't

2021-03-29 08:43 UTC, olliefr approved these changes

2021-03-29 09:05 UTC, merged

2021-03-29 09:16 UTC, nate-droid approved these changes